### ISSUE TITLE
Error when searching for an application

### ISSUE THREAD

**Issue by httsmvkcom** [redsolver/skydroid#12]
https://siasky.net/_AkxNQGwxFqMRch0cMJ9CJW4K6FN1yPPJGHatSwbqFKz7Q

Device: Pixel 4a
OS: Android 11

**Comment by redsolver** [comment]
Does this happen also when you don't click on the search icon and just wait?

**Comment by httsmvkcom** [comment]
Crash only after clicking on the search icon and waiting ~1-2 seconds

**Comment by httsmvkcom** [comment]
https://siasky.net/HADtkd6g6IXH5MDSKgmZKDoSD-pmRkJnAaKMx1Xer2VZXQ

There are errors again

**Comment by redsolver** [comment]
This should be fixed in Version 0.3.0 (https://github.com/redsolver/skydroid/releases/tag/v0.3.0), please confirm.

**Comment by httsmvkcom** [comment]
It's all good in 0.3.0
