### ISSUE TITLE
Root, Update all

### ISSUE THREAD

**Issue by bege10** [redsolver/skydroid#15]
Skydroid does not ask for root permission on the rooted device. I miss an "update all" feature.

**Comment by redsolver** [comment]
SkyFeed does have an "Update all" feature, you can enable it in the Settings if you have Shizuku Service installed (https://shizuku.rikka.app/guide/setup.html). Shizuku can be started using ADB on non-rooted devices or directly if you have root

**Comment by bege10** [comment]
I'd prefer not to have another app for this. I am having enough trouble with Magisk already. Why can't Skydroid do it as F-Droid and Aurora Store?

**Comment by redsolver** [comment]
Shizuku is also used by some other apps (https://shizuku.rikka.app/apps.html) to get access to System APIs, the advantages of using Shizuku vs direct root access are explained here: https://shizuku.rikka.app/introduction.html
Also you can install Shizuku directly using SkyDroid and get up and running in less than 1 minute if you're rooted, so I don't really see a problem here. Shizuku should not cause any trouble if you're already rooted, it's open-source and if you don't want yet another app on your homescreen, simply remove it.
