### ISSUE TITLE
"Comparison to other App Stores" gets some thing about F-Droid wrong

### ISSUE THREAD

**Issue by eighthave** [redsolver/skydroid#23]
This is not true: "All apps in the F-Droid main repo are signed and managed by F-Droid ", there are many apps published with the upstream dev's signature via the reproducible process:
https://f-droid.org/docs/Reproducible_Builds/

**Comment by redsolver** [comment]
Thank you for reporting this, I just updated the item in the comparison table. Let me know if it is correct now,

**Comment by eighthave** [comment]
looks good, thanks
