### ISSUE TITLE
[Feature Request] Adding more suggested repos

### ISSUE THREAD

**Issue by machiav3lli** [redsolver/skydroid#5]
As the lib stands, there's only two suggested collections. Adding some other prominent repositories like IzzyOnDroid, Guardian, MicroG and Bromite should ease the transition of users to the app.

That's something I could PR if you point me out to where you store their data.

**Comment by redsolver** [comment]
This is handled by the skydroid-fdroid-bridge, an issue to add more F-Droid repos already exists there: https://github.com/redsolver/skydroid-fdroid-bridge/issues/2
