### ISSUE TITLE
HTTP 502

### ISSUE THREAD

**Issue by httsmvkcom** [redsolver/skydroid#7]
![Screenshot_20210129-023930](https://user-images.githubusercontent.com/51028674/106212317-6a0e8280-61db-11eb-889f-d8e47ca92a3b.png)
When I run the application, I get a 502 error, I reinstalled the application, but it didn't help.

**Comment by redsolver** [comment]
Thank you for the report, it should be fixed now. There were some issues with the DNS servers used by the majority of SkyDroid apps.

**Comment by httsmvkcom** [comment]
No problem, it works, thanks
