### ISSUE TITLE
Translating

### ISSUE THREAD

**Issue by jakubfabijan** [redsolver/skydroid#9]
I want to translate skydroid interface to polish and Esperanto is there a way I can do it?

**Comment by redsolver** [comment]
Not yet, I will let you know as soon as multi-language support for the app interface is available.

**Comment by redsolver** [comment]
I just added internationalization support, you can submit translations for new languages by copying the english file (https://github.com/redsolver/skydroid/blob/master/assets/translations/en.yaml), editing the values and submitting a pull request. Alternatively you can just send me the translated file if you prefer that.

**Comment by redsolver** [comment]
@jakubfabijan You can help translating SkyDroid here if you're still interested: https://weblate.bubu1.eu/engage/skydroid/
